# Generated by Django 5.0 on 2023-12-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
