# Generated by Django 5.0 on 2023-12-18 13:49

import sharing.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_credentials',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secret_token',
            field=models.CharField(default=sharing.models.generate_secret_token, max_length=255, unique=True),
        ),
    ]
